### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sberryman** [alexge233/espresso_maker#2]
Just wanted to thank you for posting this code!

https://github.com/alexge233/espresso-maker/blob/master/espresso.cpp#L120-L127
That part saved me while trying to figure out how to convert a GpuMat to a tensor for Yolo v3. I know the projects are different but changing from HWC -> CHW threw me off for a while.

**Comment by alexge233** [comment]
You are welcome @sberryman! Happy it helped someone
